[project]
name = "agent-smith"
version = "0.1.0"
description = "AI agent that generates and executes code. The agent uses an MCP server to determine available resources."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fire>=0.7.1",
    "google-genai>=2.22.0",
    "mcp>=2.2.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "types-requests>=2.33.0.20260906",
]
